=== rdkcentral/zilker-sdk/source/libs/device/descriptors/WhiteList.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  -
   - Copyright 2021 Comcast Cable Communications Management, LLC
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  - http://www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -
  - SPDX-License-Identifier: Apache-2.0
  -
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="stringtype">
    <xs:restriction base="xs:string">
        <xs:minLength value = "1"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="inttype">
    <xs:restriction base="xs:positiveInteger"/>
</xs:simpleType>

<xs:simpleType name="dectype">
    <xs:restriction base="xs:decimal"/>
</xs:simpleType>
    
<xs:simpleType name="uritype">
    <xs:restriction base="xs:anyURI">
        <xs:pattern value="http://.*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="versiontype">
    <xs:restriction base="xs:string">
        <xs:minLength value = "1"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="cameraProtocoltype">
    <xs:restriction base="xs:string">
        <xs:pattern value="legacy"/>
        <xs:pattern value="openHome"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="cameraSSIDtype">
    <xs:restriction base="xs:string">
        <xs:pattern value="\(\((.+)\)_\(\[0\-9a\-fA\-F\]\)\{6\}\)"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="versionformattype">
    <xs:restriction base="xs:string">
        <xs:pattern value="legacyCamera"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="listtype">
    <xs:sequence>
        <xs:element type="versiontype" name="version" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="versionrangetype">
    <xs:sequence>
        <xs:element type="versiontype" name="from" minOccurs="1" maxOccurs="1"/>
        <xs:element type="versiontype" name="to" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="wildcardtype">
</xs:complexType>

<xs:complexType name="versionlisttype">
    <xs:choice>
        <xs:element type="listtype" name="list" maxOccurs="1"/>
        <xs:element type="wildcardtype" name="any" minOccurs="1" maxOccurs="1"/>
        <xs:element type="versionrangetype" name="range" minOccurs="1" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute name="format" type="versionformattype" use="optional"/>
</xs:complexType>

<xs:simpleType name="fimwarestringtype">
    <xs:restriction base="xs:string">
        <xs:pattern value="ota|legacy"/>
    </xs:restriction>
</xs:simpleType>
 
<xs:simpleType name="categorystringtype">
    <xs:restriction base="xs:string">
        <xs:pattern value="zigbee|camera|PhilipsHue"/>
    </xs:restriction>
</xs:simpleType>
 
<xs:simpleType name="restrictionstringtype">
    <xs:restriction base="xs:string">
        <xs:pattern value="blacklist"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="rolestringtype">
    <xs:restriction base="xs:string">
        <xs:pattern value="client|server"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="booleanstringtype">
    <xs:restriction base="xs:string">
        <xs:pattern value="true|false"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="firmwarefiletype">
    <xs:simpleContent>
        <xs:extension base="stringtype">
            <xs:attribute name="checksum" type="stringtype" use="optional"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>
    
<xs:complexType name="clustertype">
    <xs:sequence>
        <xs:element name="clusterId" type="stringtype" />
        <xs:element name="endpointId" type="stringtype" />
    </xs:sequence>
    
    <xs:attribute name="role" type="rolestringtype" use="required" />
</xs:complexType>

<xs:complexType name="attributetype">
    <xs:sequence>
        <xs:element name="attributeId" type="stringtype" />
        <xs:element name="clusterId" type="stringtype" />
        <xs:element name="endpointId" type="stringtype" />
    </xs:sequence>
    
    <xs:attribute name="role" type="rolestringtype" use="required" />
</xs:complexType>

<xs:complexType name="commandtype">
    <xs:sequence>
        <xs:element name="commandId" type="stringtype" />
        <xs:element name="clusterId" type="stringtype" />
        <xs:element name="endpointId" type="stringtype" />
    </xs:sequence>
    
    <xs:attribute name="role" type="rolestringtype" use="required" />
    <xs:attribute name="isManufacturerSpecific" type="booleanstringtype" />
    <xs:attribute name="manufacturerId" type="inttype" />
</xs:complexType>

<xs:complexType name="metadatatype">
    <xs:attribute name="name" type="stringtype" />
    <xs:attribute name="value" type="stringtype" />
</xs:complexType>

<xs:complexType name="firmwaretype">
    <xs:sequence>
        <xs:element name="version" type="versiontype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="filename" type="firmwarefiletype" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="zigbeefirmwaretype">
    <xs:complexContent>
        <xs:extension base="firmwaretype">
            <xs:sequence>
                <xs:element name="type" type="fimwarestringtype" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="endpointidstype">
    <xs:sequence>
        <xs:element name="endpointId" type="stringtype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="clusterstype">
    <xs:sequence>
        <xs:element name="cluster" type="clustertype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="attributestype">
    <xs:sequence>
        <xs:element name="attribute" type="attributetype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="commandstype">
    <xs:sequence>
        <xs:element name="command" type="commandtype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="metadatalisttype">
    <xs:sequence>
        <xs:element name="metadata" type="metadatatype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="zigbeerestrictionstype">
    <xs:sequence>
        <xs:element name="endpointIds" type="endpointidstype"  minOccurs="0"/>
        <xs:element name="clusters" type="clusterstype"  minOccurs="0"/>
        <xs:element name="attributes" type="attributestype"  minOccurs="0"/>
        <xs:element name="commands" type="commandstype"  minOccurs="0"/>
    </xs:sequence>
    
    <xs:attribute name="restrictionType" type="restrictionstringtype" use="required" />
</xs:complexType>

<xs:complexType name="firmwareversionlisttype">
    <xs:sequence>
        <xs:element name="version" type="versiontype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="clusterlisttype">
    <xs:sequence>
        <xs:element name="mfgId" type="xs:string"></xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"></xs:attribute>
</xs:complexType>

<xs:complexType name="zigbeemfgidstype">
    <xs:sequence>
        <xs:element name="cluster" type="clusterlisttype" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="devicedescriptortypebase">
    <xs:sequence>
        <xs:element name="uuid" type="stringtype" minOccurs="1"/>
        <xs:element name="description" type="stringtype" minOccurs="0" maxOccurs="1"/> 
        <xs:element name="manufacturer" type="stringtype"/>
        <xs:element name="model" type="stringtype"/>
        <xs:element name="hardwareVersions" type="versionlisttype"/>
        <xs:element name="firmwareVersions" type="versionlisttype"/>
        <xs:element name="minSupportedFirmwareVersion" type="versiontype" minOccurs="0" maxOccurs="1"/>
        <xs:element name="metadataList" type="metadatalisttype" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>
    
<xs:complexType name="legacyzigbeedevicedescriptortype">
    <xs:sequence>
        <xs:element name="uuid" type="stringtype" minOccurs="1"/>
        <xs:element name="description" type="stringtype" minOccurs="0" maxOccurs="1"/> 
        <xs:element name="category" type="categorystringtype"/>
        <xs:element name="manufacturer" type="stringtype"/>
        <xs:element name="model" type="stringtype"/>
        <xs:element name="hardwareVersions" type="versiontype"/>
        <xs:element name="firmwareVersions" type="versiontype"/>
        <xs:element name="minSupportedFirmwareVersion" type="versiontype" minOccurs="0" maxOccurs="1"/>
        <xs:element name="metadataList" type="metadatalisttype" minOccurs="0"/>
        <xs:element name="latestFirmware" type="zigbeefirmwaretype" minOccurs="0"/>
        <xs:element name="restrictions" type="zigbeerestrictionstype" minOccurs="0"/>
        <xs:element name="mfgIds" type="zigbeemfgidstype" minOccurs="0" maxOccurs="1"/>
        <xs:element name="cascadeAddDeleteEndpoints" type="booleanstringtype" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="cameradevicedescriptortype">
    <xs:complexContent>
        <xs:extension base="devicedescriptortypebase">
            <xs:sequence>
                <xs:element name="latestFirmware" type="firmwaretype" minOccurs="0"/>
                <xs:element name="protocol" type="cameraProtocoltype" minOccurs="1" maxOccurs = "1"/>
                <xs:element name="motion" type="cameramotiondescriptortype" minOccurs="0" maxOccurs = "1"/>
                <xs:element name="ssid" type="cameraSSIDtype" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="cameramotiondescriptortype">
    <xs:sequence>
        <xs:element name="enabled" type="booleanstringtype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="sensitivityLevel" type="motionsensitivitydescriptortype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="detectionThreshold" type="motiondetectthreshdescriptortype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="regionOfInterest" type="motionroidescriptortype" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="motionsensitivitydescriptortype">
    <xs:sequence>
        <xs:element name="low" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="med" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="high" type="inttype" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="motiondetectthreshdescriptortype">
    <xs:sequence>
        <xs:element name="low" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="med" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="high" type="inttype" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="motionroidescriptortype">
    <xs:sequence>
        <xs:element name="width" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="height" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="bottomCoord" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="topCoord" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="leftCoord" type="inttype" minOccurs="1" maxOccurs="1"/>
        <xs:element name="rightCoord" type="inttype" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="zigbeedevicedescriptortype">
    <xs:complexContent>
        <xs:extension base="devicedescriptortypebase">
            <xs:sequence>
                <xs:element name="latestFirmware" type="zigbeefirmwaretype" minOccurs="0"/>
                <xs:element name="restrictions" type="zigbeerestrictionstype" minOccurs="0"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
    
<xs:complexType name="devicedescriptorlisttype">
    <xs:sequence>
        <xs:element name="DeviceDescriptor" type="legacyzigbeedevicedescriptortype" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="ZigbeeDeviceDescriptor" type="zigbeedevicedescriptortype" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="CameraDeviceDescriptor" type="cameradevicedescriptortype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>

    <xs:attribute name="version" type="stringtype" use="required" />
</xs:complexType>

<xs:element name="DeviceDescriptorList" type="devicedescriptorlisttype" />

</xs:schema>

=== rdkcentral/zilker-sdk/tools/zith/src/main/resources/bundle/lists/WhiteList-Converge-Updated.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -
   - Copyright 2021 Comcast Cable Communications Management, LLC
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  - http://www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -
  - SPDX-License-Identifier: Apache-2.0
  -
  -->
<DeviceDescriptorList version="7.3.0-020619" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WhiteList.xsd">
    <!-- Converge DDL -->

    <CameraDeviceDescriptor>
        <uuid>4d756c74-694d-6564-6961-7894b4fd1462</uuid>
        <description>Sercomm XCAM2</description>
        <manufacturer>Sercomm</manufacturer>
        <model>SCHC2AWW</model>
        <hardwareVersions><any/></hardwareVersions>
        <firmwareVersions>
            <list>
                <version>3.0.02.54</version>
                <version>3.0.02.20</version>
            </list>
        </firmwareVersions>
        <minSupportedFirmwareVersion>3.0.02.20</minSupportedFirmwareVersion>
        <latestFirmware>
            <version>3.0.02.54</version>
            <filename>SERXW3_2.1p6s1_PRODsd.bin</filename>
        </latestFirmware>
        <protocol>openHome</protocol>
        <motion>
            <enabled>false</enabled>
            <sensitivityLevel>
                <low>70</low>
                <med>80</med>
                <high>90</high>
            </sensitivityLevel>
            <detectionThreshold>
                <low>27</low>
                <med>22</med>
                <high>8</high>
            </detectionThreshold>
            <regionOfInterest>
                <width>16</width>
                <height>16</height>
                <bottomCoord>240</bottomCoord>
                <topCoord>479</topCoord>
                <leftCoord>96</leftCoord>
                <rightCoord>543</rightCoord>
            </regionOfInterest>
        </motion>
    </CameraDeviceDescriptor>

</DeviceDescriptorList>
